### ISSUE TITLE
parse filename with quote

### ISSUE THREAD

**Issue by victorenator** [andrewrk/node-multiparty#101]
Browser sent header:
Content-Disposition: form-data; name="file"; filename="100129-03\"100129.jpg"

It parsed as:
originalFilename: '"100129.jpg'

But expected:
originalFilename: '100129-03"100129.jpg'

**Comment by andrewrk** [comment]
looks like we should use this module: https://github.com/jshttp/content-disposition

to parse content-disposition instead of using the naive regex that is currently in place.

**Comment by dougwilson** [comment]
So there are a few "quirks" for parsing the CD header in multipart vs http (because... browsers :/). If you plan to add it, I believe I at least started hacking on adding a "multipart quirks mode" and can wrap it up ASAP :)

**Comment by andrewrk** [comment]
Nice! Yeah if you do that we should use it in multiparty.

**Comment by dougwilson** [comment]
Cool. That was the whole reason I was doing in the first place :) But now I have motivation since it seems you're likely to end up using it, haha :D

**Comment by andrewrk** [comment]
At the very least I'm happily using it for groove basin: https://github.com/andrewrk/groovebasin/blob/master/package.json#L24
:-)

**Comment by andrewrk** [comment]
nice. I think this might be a good candidate for a minor version bump since the change in parsing behavior might be considered "risky".

**Comment by dougwilson** [comment]
Ah, yea, I suppose so, lol. What about the change on waiting to emit the `error` on `part` until after we actually handed `part` to the user to attach a listener (wow, a mouthful)? 07fabc525ddd72a6b9d9dc60073f04a7121e2e04

Seems like a patch release would be good, or just roll up into the minor?

**Comment by andrewrk** [comment]
hmm on second thought maybe we can call these both bugfixes. if there's another bug revealed, we'll fix those too.

**Comment by andrewrk** [comment]
damn we're almost down to 0 issues. that's almost motivating me to make it the rest of the way.

**Comment by dougwilson** [comment]
lol, yea, all that's left in the issues are feature requests. Any objection to the current master being 4.1.2?

**Comment by andrewrk** [comment]
no objection :)
