### ISSUE TITLE
stream ended unexpectedly

### ISSUE THREAD

**Issue by freesuraj** [andrewrk/node-multiparty#102]
It's appearing in the following different scenarios:
1. Whenever there's a file in the form, and I don't do any attachment, 
2. If I attach image in the file
However, if I attach other files (like zip) it does recognize.
I'm trying it on a sails application.
Has anybody encountered it before ?
The code example is the same one posted on the github.

**Comment by dougwilson** [comment]
This error typically means the client you are using has a bug in it.

**Comment by johnmanoahs** [comment]
I was able to solve the torturous *"stream ended unexpectedly"* error after hours and hours of debugging. The error magically vanished after I commented out **app.use(fileUpload());** from my node server page. Not sure why but it works.

**Comment by pankajtiwari1983** [comment]
@johnmanoahs Thanks, after hours of debugging myself, saw your comment and observed the same thing.
The error disappears on commenting out the mentioned line.

**Comment by OnclickSell** [comment]
I think it's because the fileUpload() manipulate the request object and since the objects are reference type, multiparty cannot parse it.
