### ISSUE TITLE
missing detail in 'field' event documentation (implementing this event disables emitting fields to 'part' event)

### ISSUE THREAD

**Issue by jakubknejzlik** [andrewrk/node-multiparty#104]
Hi,
I've discovered cool feature (from examples): if 'field' event is listened to, all field parts  are not emitted in 'part' event(just file parts), so the whole code is much cleaner.

Although it's nice, I couldn't find any mention about it in README.

**Comment by dougwilson** [comment]
It is in the readme:

> autoFields - Enables field events and disables part events for fields. This is automatically set to true if you add a field listener.

**Comment by jakubknejzlik** [comment]
Oh damn, my bad I've missed the connection between those two.

Thank for quick response! :)

**Comment by dougwilson** [comment]
No problem-o
