### ISSUE TITLE
form.on("part") is called repeatedly?

### ISSUE THREAD

**Issue by daniel-shin1104** [andrewrk/node-multiparty#109]
Hi I've just started looking at this library, and wasn't sure if the form.on("part", listener) is called repeatedly or called once when the form data is first found. I need a clarification since i'm making small module to abstract all multipart parsing. I need it to basically accept `req` and callback function and call callback function with readable stream when is found.

It would kinda break my api if callback was called repeatedly with 'partial' form stream, which I presume is the case since you can access its `bytecount` through passed `part`. 

I just need a nice one readable stream that I can pass along to other parts of my application.

Is this true? and if so is there a way that I can receive one readable stream instead of partials?

Thanks you in advance!

**Comment by dougwilson** [comment]
Hopefully the docs make it clear, and if not, let me know what we need to change to clarify: https://github.com/andrewrk/node-multiparty#part-part

The `part` event is emitted for every single part on the form. A "part" is either a field or a file. If a form contains 4 files and 1 field, then the `part` event will be emitted 5 times.

**Comment by dougwilson** [comment]
If you want to just get one callback when everything is done, please see the example in the readme: https://github.com/andrewrk/node-multiparty#usage

**Comment by daniel-shin1104** [comment]
Thanks for quick response! It probably is more due to the fact that I never had to deal with multi-part previously and thus unfamiliar. So according to your first comment, does that mean that if I upload one image file from client, `part` event will be called twice? once for field and once for raw data?

**Comment by daniel-shin1104** [comment]
Or is it arbitrarily partitioned by what client decides to send per request by its file size or whatnot? 

Also as to your second comment, does that temporarily save to disk or save in memory?

**Comment by dougwilson** [comment]
> So according to your first comment, does that mean that if I upload one image file from client, part event will be called twice? once for field and once for raw data? 

No, if there is _truely only one image and nothing else in the form_ then it'll only be called once. If there is something else in the form, like a field, then you'll get a second call for that other item.

> Or is it arbitrarily partitioned by what client decides to send per request by its file size or whatnot? 

It's not arbitrarily, it's literally once per each "part" of the form. A "part" is either a field or a file. If a form contains 4 files and 1 field, then the part event will be emitted 5 times.

> Also as to your second comment, does that temporarily save to disk or save in memory?

To disk, so a client that sends you a 4GB file won't crash your app.

**Comment by daniel-shin1104** [comment]
Aha! Thanks for your clarification. Just one last question. Is there a way that I can enforce / check if the `part` is called once only? that is, client sends one thing only per each request. This is just to make module compliant with what other parts of my application expect it to do.

I guess I can set up a simple flag variable and check it but anything internally implemented?

**Comment by dougwilson** [comment]
So remember, you can always use the callback style used in the example I linked to _instead of using the part event_. If you really want to still use the part event and you only ever want a single part (I assume you want that one and only one to be a file?), just use the restricting options we provide: https://github.com/andrewrk/node-multiparty#multipartyform

Set `maxFields` to 1.

**Comment by daniel-shin1104** [comment]
Yeah I guess the callback style makes more sense as to my case. Thanks for your help.

Great work btw!
