### ISSUE TITLE
Not able to keep original file name

### ISSUE THREAD

**Issue by becjit** [andrewrk/node-multiparty#110]
Hi,
  A random file name is always getting generated. Would like to keep the original one. Is this supported?
~Abhijit

**Comment by andrewrk** [comment]
The original filename is provided. Rename the random name to the filename you want. Be sure to watch out for name collisions and race conditions.

**Comment by becjit** [comment]
Hi Andrew,
  At what event I should be doing that. Right now I am doing that in
"close" using fs. Is that the best way to do that?
In formidable there was one fileBegin event which I dont see here. Is it
left out by choice?
Thanks,
Abhijit

**Comment by andrewrk** [comment]
You could also use the 'part' API and direct the incoming stream directly into the filename of your choice. When you receive a 'part' event, the `filename` property is the user-provided filename. Keep in mind that using this filename unfiltered is a security concern.
