### ISSUE TITLE
Is it possible to expose 'abort' on part or form

### ISSUE THREAD

**Issue by kevbook** [andrewrk/node-multiparty#115]
The reason is, when you are just pipe-ing data, lets say to S3, one can keep a track on maxBytes, and abort it. Straight pipe-ing without maxBytes can be dangerous.

**Comment by wlingke** [comment]
Can't you look at `part.byteCount` to see how large the file is?

**Comment by dougwilson** [comment]
Hi @kevbook, can you clarify the request? Are you asking if it's possible to add a `part.abort()` method? If this is correct, can you explain what exactly you would expect it to do?

**Comment by kevbook** [comment]
This was a while ago, I don't think its needed anymore.
