### ISSUE TITLE
How to respond to errors inside on('part')?

### ISSUE THREAD

**Issue by wlingke** [andrewrk/node-multiparty#116]
I have to perform some async operations inside the `part` handler and sometimes these can return errors. If there are errors, I'd like to end the response (with a `res.end()`). The response occurs however, after a while, I notice that I get an error from multiparty that says "Error: Request aborted".

What is the proper way of ending a response while inside `part`?

**Comment by alon-argus** [comment]
May I ask what did you end up with?

**Comment by colm-mcqs** [comment]
I have done it by 

````
     form.on('part', function (part) {
        part.on('error', function (err) {
            //handle error
  
        });
        // if no error, pipe part into file modification/save stream
    });
````

Any help?

**Comment by wlingke** [comment]
Yes - I forgot I solved this issue a while back.
