### ISSUE TITLE
crash on client abort

### ISSUE THREAD

**Issue by ericgj** [andrewrk/node-multiparty#118]
Despite having a form 'error' event handler, I get this crash when aborting an upload from the client:

    events.js:85
          throw er; // Unhandled 'error' event
                ^
    Error: Request aborted
        at IncomingMessage.onReqAborted (/media/sf_dev-home/forks/nfff/examples/file-uploader/node_modules/multiparty/index.js:183:17)
        at IncomingMessage.emit (events.js:104:17)
        at abortIncoming (_http_server.js:279:11)
        at Socket.socketOnEnd (_http_server.js:393:7)
        at Socket.emit (events.js:129:20)
        at _stream_readable.js:908:16
        at process._tickCallback (node.js:355:11)

I tried adding 
  - a form 'aborted' handler, 
  - an 'abort' handler on the http req stream,
  - an 'error' and 'aborted' handler on the part stream, 

but still get this.

Am I missing something obvious?

**Comment by dougwilson** [comment]
Hm, you sound like everything is fine. Can you post the code you are using?

**Comment by ericgj** [comment]
It's just for testing purposes so is kind of slapped together, but would like to get to the bottom of the abort error.

```js
  req.on('abort', function(){ 
    respond(400, 'Error receiving', res); 
  });

  if (req.url == '/upload' && req.method == 'POST'){
    var form = new multipart.Form();
    
    form.on('part', function(part){
      if (!part.filename) return;

      try {
        var fsOut = path.join(__dirname, UPLOADDIR, part.filename);
        var out = fs.createWriteStream(fsOut);
        part.pipe(out);
        console.log('-> ' + fsOut);
      } catch (e) {
        console.error('-X ' + fsOut);
        console.error("Upload error: " + e.message);
        respond(500, e.message, res);
      }

    });
    
    form.on('error', function(){
      respond(400, 'Unable to parse as multipart', res);
    });

    form.on('close', function(){
      respond(200, 'OK', res);
    });

    form.parse(req);

    return;
  }
  
  // otherwise, static file serving
  // ....

function respond(status, msg, res){
  res.writeHead(status, {'content-type': 'text/plain'});
  res.write(msg);
  res.end();
}

```

**Comment by dougwilson** [comment]
I think I see the issue: I don't see you adding any `error` listener on the `part` stream.

**Comment by ericgj** [comment]
I thought I got the same error when I had that, but trying it again now I see I get a different error related to trying to write to the closed response stream.  So I got it working adding:

```js
      part.on('error', function(){
        res.on('error', function(){});
        respond(400, 'Error receiving', res);
      });
```

Thanks a lot.

**Comment by jweather** [comment]
So how do I handle this when using a 'file' handler?
````
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Request aborted
    at IncomingMessage.onReqAborted (C:\...\node_modules\multiparty\index.js:183:17)
    at IncomingMessage.EventEmitter.emit (events.js:92:17)
    at abortIncoming (http.js:1892:11)
    at Socket.socket.onend (http.js:1984:7)
    at Socket.g (events.js:175:14)
    at Socket.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:910:16
    at process._tickCallback (node.js:415:13)
````

**Comment by dougwilson** [comment]
@jweather without seeing your code, the best suggestion I have is that you didn't properly attach an `error` listener to the `form` object or something.

**Comment by jweather** [comment]
Got it... I'm a little surprised it crashes the whole app without an error handler set -- maybe I'm spoiled by express's default error handling, which only bails on that request.

**Comment by dougwilson** [comment]
@jweather, yea, that is just how Node.js event emitters work: they will crash your app by default unless you add `error` listeners to every single event emitter you ever create. Kinda sucks in long-running servers.

**Comment by alextse** [comment]
hi there, I'm having the same problem with the following code, any idea please?

`router.post("/upload", function (req, res, next) {
    let form = new multiparty.Form();

    form.on("error", function (err) {
        console.error("form error", err);
        res.status(err.statusCode).end();
    });

    form.on("part", function (part) {
        if (!part.filename) {
            part.resume();
            return;
        }

        part.on("error", function (err)  {
            console.err("part error", err);
            res.status(err.statusCode).end();
        });

        let fd = new FormData();
        fd.append("image", part, {
            filename: part.filename,
            contentType: part.headers["content-type"],
            knownLength: part.byteCount
        });
        fd.submit(submitOptions, function (err, res0) {
            if (err) {
                console.error(err);
                res.status(err.statusCode).end();
            }

            res0.pipe(res);
        });
    });

    form.parse(req);
});`

**Comment by emelineL** [comment]
I'm having the same problem, even though I have event handlers for `part.on('error')` and `form.on('error')`. This is the code I'm running:

```  form.on('field', function (field, value) {
    fileData[field] = value;
  });

  form.on('part', function (part) {
    if (part.filename) {
      fileData.file = part;
      uploadFunction(...);
    }
    part.on('error', function (err) {
      apiUtils.respond(res, err);
    });
  });

  form.on('progress', function () { res.writeContinue(); });

  form.on('error', function (err) {
    apiUtils.respond(res, err);
  });
  
  form.parse(req);
```
