### ISSUE TITLE
“Error: socket hang up” while streaming using multiparty and request modules

### ISSUE THREAD

**Issue by qnimate** [andrewrk/node-multiparty#122]
Here is the code:
```js
var app = require("express")();
var multiparty = require("multiparty");
var request = require("request");
var ims = require("imagemagick-stream");
var fs = require("fs");
var Busboy = require('busboy');

app.post('/submit', function(httpRequest, httpResponse, next){

    var form = new multiparty.Form();

    form.on("part", function(part){
        if(part.filename)
        {
            var formData = {
                thumbnail: {
                    value:  part,
                    options: {
                        filename: part.filename,
                        contentType: part["content-type"]
                    }
                }
            };

            request.post({url:'http://localhost:7070/store', formData: formData}, function (err, httpResponse, body) {
                if(err) {
                    return console.error('upload failed:', err);
                }

                console.log('Upload successful!  Server responded with:');
            });
        }
    })

    form.on("error", function(error){
        console.log(error);
    })

    form.parse(httpRequest);    

});

app.get('/', function(httpRequest, httpResponse, next){ 
    httpResponse.send('<form action="http://localhost:9090/submit" method="post" enctype="multipart/form-data"><input type="file" name="file" /><input type="submit" value="xxx" /></form>');
});


app.listen(9090);
```

Here I am uploading the file submitted by user to another server without saving it on disk.

I get error upload failed: { [Error: socket hang up] code: 'ECONNRESET' }.

And on the server running on port 7070 I get error Error: stream ended unexpectedly

If I replace part in value:part with a filesystem readable stream then it works fine.

I think its missing content-length header. But when I add it I get a different error.

Thanks in advance.

**Comment by dougwilson** [comment]
Hi! The reason is that `part` is a stream, not a type that the `request` module accepts in that part of the object structure. It seems like the main issue here is how to use the `request` module. I'm not that familiar with it, but if you have any specific questions for how to get a specific piece of information from the `part` object, let me know.

**Comment by vsc-github** [comment]
For anyone looking for a solution to this problem [refer this](https://github.com/request/request/issues/1801).
