### ISSUE TITLE
Unhandled 'error' event.

### ISSUE THREAD

**Issue by Alanz2223** [andrewrk/node-multiparty#124]
Hello I have forked the module and I am trying to customize it to fit my app's operation. I would like to have a function called whenever there is a new file uploaded and that function, depending on the name of the file is suppossed to specify where to place the file as well as its name. Upon creating a new multiparty.Form() object I pass in the configurations along with all the function to be called. The options object looks like this.
```
var multiparty = require('multiparty')
var form = new multiparty.Form({
         maxFilesSize : maximumSize,
        onFileUploadStart : function(filestream,callback)
                {
                     cb(newFileUploaded(filestream))
                }
});
```
Then within the multiparty constructor I set the property
```
self.onUploadStart = options.onFileUploadStart;
```
now whenever there is a new file the handleFile(self,stream) function is called, these are its internals
```
function handleFile(self, fileStream) {
  if (self.error) return;

 self.onUploadStart(function(options){
  
   if(typeof(options) === 'string')
   {
     self.handleError(createError(400,options));
   }
   else
   {
      commenceFileProcessing(self,filestream,options)
   }


});
  
}
```

what the former function basically does is invoke its `onUploadStart()` property, in there I basically check the file type and non related processing. The important bit is that if any of the processing fails, I return a string, if it succeeds then I return an object denoting where to upload the file to and what to name it.

Right after I create the form object I attached the 'error' listener like so
```
form.on('error',function(err){
 //error handling;
})
```
The issue comes whenever it does fail, my server crashes and it logs 
```
throw er; // Unhandled 'error' event
```
even though I clealy have attached the listener, and what is even more strange is that If the error is say a file entity too large, or something else generated within the form. The error listener is properly called. So I thought that it might be an issue of scope, so I tried setting the onUploadStart property after the form.on('error',cb) handler but that did not help neither.

Any suggestions are appreciated, thanks.

**Comment by dougwilson** [comment]
You have to attach an error listener to the `fileStream` object as well (last note in https://github.com/andrewrk/node-multiparty#part-part). Most likely, it is an error being emitted on `fileStream` that is crashing your process.
