### ISSUE TITLE
is there a way to force incoming files to a certain filetype?

### ISSUE THREAD

**Issue by colm-mcqs** [andrewrk/node-multiparty#125]
In my case, I have uploaded images that I need to convert to png if they are jpg or gif. Is there a built in way in node-multiparty to do this? 

Big fan of the module otherwise @andrewrk and other contribs.

**Comment by andrewrk** [comment]
In software, it's best to keep the scope limited and use [modular programming](https://en.wikipedia.org/wiki/Modular_programming). Given this, multiparty only tries to solve parsing multipart uploads and *nothing else*. The task of converting image formats is left up to you to solve. That being said, there are other modules out there whose purpose actually is for converting images and you could use one of those in conjunction with multiparty to accomplish your goal.

**Comment by colm-mcqs** [comment]
Thanks, I'll convert them with another module. Just didn't want to pull in another dependency if it was built into this!
