### ISSUE TITLE
Does multiparty respect the order in which keys are appended to a formdata object?

### ISSUE THREAD

**Issue by Alanz2223** [andrewrk/node-multiparty#127]
I am currently experiencing issues where I append a crucial value to the start of a formdata object and following that I append some files, the 'file' event is firing before the 'field' event. Could this be caused by how multiparty is implemented internally? is there any way to fix this issue without having to split the request into two? Thanks.

**Comment by dougwilson** [comment]
The events should be firing in the physical order they appear in the HTTP payload. Can you use Fiddler or a similar tool to capture the multipart payload and post it here?

**Comment by Alanz2223** [comment]
Yea that was the issue, I thought I was appending the values in the correct order but I was not, I downloaded fiddler and was able to resolve the issue quickly. Thanks for your help, you may close this.

**Comment by dougwilson** [comment]
No problem at all!
