### ISSUE TITLE
How could I deal with asynchronous tasks before close event?

### ISSUE THREAD

**Issue by zetta24** [andrewrk/node-multiparty#128]
I am currently struggling with a synchronization problem that is critical for my route to work correctly. In my app I receive an array of files to delete and also I might attach some new files to upload with it, however since the file deletion is done asynchronously the 'close' event fires before my app invokes the callback from the delete operation, where I check for errors and receive other information. Is there a way I could delay the close event, so that it fires after my callback is invoked? I am trying to avoid making the delete operation synchronous.

**Comment by dougwilson** [comment]
Hi! There is no such thing as a delayed event, as that is not part of the Node.js event emitter model. To me, it sounds like all you want to do is write JavaScript to sync two callback together. The `after` module (https://www.npmjs.com/package/after) is a nice, easy way to accomplish this. If you would like an example of this, I would probably need to see an example of your code to craft one up for you.

**Comment by andrewrk** [comment]
I made a module for this too :-) https://www.npmjs.com/package/pend
