### ISSUE TITLE
Error file=...node_modules/multiparty/index.js, function=IncomingMessage.onReqAborted, line=183

### ISSUE THREAD

**Issue by dingodail** [andrewrk/node-multiparty#135]
Help

I used multiparty in my project to upload two files on the server, if the files are larger than 4 MB I get this error:

Error file=...node_modules/multiparty/index.js, function=IncomingMessage.onReqAborted, line=183 method=onReqAborted, native=false, column=13, file=events.js, function=emitNone, line=67, method=null, native=false, column=7, file=events.js, function=IncomingMessage.emit, line=166, method=emit, native=false, column=11, file=_http_server.js, function=abortIncoming, line=280, method=null, native=false, column=5, file=_http_server.js, function=Socket.serverSocketCloseListener, line=293, method=serverSocketCloseListener, native=false, column=20, file=events.js, function=emitOne, line=82, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=169, method=emit, native=false, column=12, file=net.js, function=TCP._onclose, line=469, method=_onclose, native=false], stack=[Error: Request aborted, at IncomingMessage.onReqAborted (/root/teachbyapp/node_modules/multiparty/index.js:183:17), at emitNone (events.js:67:13), at IncomingMessage.emit (events.js:166:7), at abortIncoming (_http_server.js:280:11), at Socket.serverSocketCloseListener (_http_server.js:293:5), at emitOne (events.js:82:20), at Socket.emit (events.js:169:7), at TCP._onclose (net.js:469:12)]

I use node js express an multiparty this is my code: and i upload file with form that contains

2 input text
2 input file

typy form multipart/form-data'

And this is my code
```js
app.post('/objcre', function (req, res) {
var token = req.session.token_objst;
var multiparty = require("multiparty");
var user = req.session.email;

var form = new multiparty.Form();
var nameset = "";
var descset = "";
form.on("field", function (name, value) {
    if (name === "objname") {
        nameset = value;
    }
    ;
    if (name === "objdescr") {
        descset = value;
    }
    ;
});
var imgfile = '';
form.on("part", function (part) {
    if (part.filename) {
        var source_path_file = '';
        if (part.name === 'uplimg') {
            source_path_file = './public/image/' + part.filename;
            var resizename = source_path_file.substr(0, source_path_file.lastIndexOf('.')) + '-res' + source_path_file.substr(source_path_file.lastIndexOf('.'));
            var stream = part.pipe(fs.createWriteStream(source_path_file));
            stream.on('finish', function () {
                var orifilename = part.filename;
                imgfile = config.img_dir + orifilename.substr(0, orifilename.lastIndexOf('.')) + '-res' + orifilename.substr(orifilename.lastIndexOf('.'));
                easyimg.resize({
                    src: source_path_file,
                    dst: resizename,
                    width: config.img_width,
                    height: config.img_height
                }).then(
                    function (image) {
                        logger.info('Resized and cropped: ' + imgfile + ' ' + image.width + ' x ' + image.height);
                        fs.unlink(source_path_file, function () {
                        });
                    },
                    function (err) {
                        logger.error("routesobj. Function /objcre error " + e);
                        //console.log(err);
                    }
                );
            });
            part.on('error', function(){
                res.on('error', function(){});
                respond(400, 'Error receiving', res);
            });
            //part.resume();
        } else {
            source_path_file = './public/image/' + part.filename;
            console.log("Creo il file");
            var stream = part.pipe(fs.createWriteStream(source_path_file));
            stream.on('finish', function () {
                console.log("Fine creazione file");
                var message = "Object created successfully";
                res.render('objcreate.ejs', {
                    //res.render('objcreate.ejs', {
                    message: message
                });
            });
            part.on('error', function(){
                res.on('error', function(){});
                respond(400, 'Error receiving', res);
            });
            //part.resume();
        }
        ;
    }
    ;
});
form.on("error", function (error) {
    var message = "Error Object upload";
    res.render('objcreate.ejs', {
        //res.render('objcreate.ejs', {
        message: message
    });
    logger.error("routesobj. Function /objcre error " + error);
    //console.log(error);
});
form.parse(req);

});
```
thank you so much

**Comment by dougwilson** [comment]
Hi @dingodail, that error is because the client is aborting the request for whatever reason. It's possible that the upload it taking too long, or that you are just not responding to the client, I'm not sure.

**Comment by nfraenkel** [comment]
hey @dougwilson,

So I have been running into the same problem as well -- if a file is too large / if the upload takes "too long" (what appears to be 1.5-2 mins), I get the same "Request Aborted" error as described above. 


Any idea why this happens / where this timeout length is specified? How can I either increase this timeout value or have the connection open indefinitely? Thanks in advance for your help :(

**Comment by nfraenkel** [comment]
jk figured it out -- it turns out node's default request timeout time is 2 mins, so for my upload endpoints, i overrode the timeout value to be 10 mins:
```
app.use(function (req, res, next) {
    if (_.contains(specialRoutes, req.url)) {
      res.setTimeout(60000, function() {
          res.send(408);
        });
      return next();
    }
```
