### ISSUE TITLE
Content type based on magic number ??

### ISSUE THREAD

**Issue by maxcc0** [andrewrk/node-multiparty#136]
Is there a way to know the content type/ file type in form.on('part', fn{}) ??
My requirement is that I want to check that the file extension and file content are in sync.

**Comment by dougwilson** [comment]
Hi @maxcc0, if you want to guess the content type based on the file's contents, you may want to use a module like `mmmagic` (https://www.npmjs.com/package/mmmagic) or even `stream-mmmagic` (https://www.npmjs.com/package/stream-mmmagic) if you want to do it before writing out the entire file to disk.
